groundwork code from last week
zenna/DemoSim.jl pull request #3
Opened 2021-01-13 02:13 UTC by varmichelle

2021-01-13 23:11 UTC, zenna requested changes
Small changes annotated here.  In addition:

- Add some tests
- Add some more comments
- Change JuliaWorld to DemoSim everywhere relevant (including filenames)
-

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +    preferences::Dict{Space,Integer}
Use `Int` instead of `Integer`

For more generality you could make `Agent` a parametric type `Agent{T <: Integer}`

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +
export the user facing functions

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +function generategrid()
By convention, Julia functions which produce random output generally take the rng object as an explicit object.
This is useful for making your code repeatability, and we actually exploit this feature to do probabilistic inference.

Explicitly pass in the `rng` object

```julia
using Random: AbstractRNG, default_rng
generategrid(rng::AbstractRNG)
   ...
   rand(rng, [grass, rock, water, dirt], ...(
   ...
end

# Default case
generategrid() = generategrid(Random.default_rng())
```

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +    ITERS = 20
This and other parameters should be keyword arguments (with defaults)

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +    ITERS = 20
e.g. resolution

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +    for t in 1:10
10 should be a kwarg

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +        @show grid
remove these @shows

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +using GLMakie
In most situations you should prefer `Import GLMakie` then `GLmakie.somefunction()` or `using GLMakie: somefunction, some other function` over `using GLMakie` which includes everything

2021-01-13 23:11 UTC, zenna commented on Project.toml
> +name = "JuliaWorld"
Change to DemoSim

2021-01-13 23:11 UTC, zenna commented on Project.toml
> +authors = ["Amber Li <amli@mit.edu>"]
Add Michelle as an author

2021-01-13 23:11 UTC, zenna commented on src/JuliaWorld.jl
> +
For (at least) every exported function add a docstring

2021-01-15 23:58 UTC, amburger66 commented on src/JuliaWorld.jl
> +function generategrid()
why do we use an overloaded method here, rather than having the rng be a kwarg with a default value?

2021-01-18 14:35 UTC, merged